name: '百度贴吧签到'

on:
    workflow_dispatch:
    schedule:
        - cron: "5 16,22 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: main
jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
      - name: '百度贴吧签到开始'
        env:
          BDUSS: ${{ secrets.BDUSS }}
          SYNCURL: https://github.com/ghosx/tieba/main.py
        run: python main.py
